### ISSUE TITLE
Project Motivation & Objective

### ISSUE THREAD

**Issue by hmc0105** [osamhack2022/APP_FreshPlus_TakeCareMyRefrigerator#19]
### Introduction
냉장고를 부탁해 프로젝트는 병영생활 속 냉장고 유통기한 관리, 이름 주기의 번거로움 등의 문제를 해결하기 위해 기획된 국방오픈소스아카데미 해카톤 프로젝트입니다. FreshPlus라는 이름의 Flutter 기반 어플리케이션 개발을 통해 솔루션을 제공하고자 합니다.

**Comment by hmc0105** [comment]
이 Issue가 완성되면, 이를 활용해서 Readme 파일로 이용하고자 합니다.

**Comment by Tim-Lee0001** [comment]
### Motivation

"군대에서 바나나우유 마시기" 참 어렵습니다. 

군대에서 바나나우유를 마시려면 첫번째, PX에서 바나나우유를 삽니다. 두번째, 라벨에 유통기한과 이름을 씁니다. 세번째, 라벨을 우유에 붙입니다. 네번째, 유통기한 전에 냉장고에서 찾습니다. 다섯번째, 마십니다. 마지막으로, 넣을 때 붙였던 라벨을 떼서 분리수거 합니다.

각자 집에서 각자 냉장고를 사용했다면 절대 하지 않을 과정을 거쳐야 겨우 바나나우유를 마실 수 있었습니다.

이는 군조직특성상 신선식품에 대한 철저한 관리가 필요하여 생겨났습니다. 그러나 그 과정이 불편한 만큼, 오히려 놓치는 식품들도 생겨났습니다.

이렇게 불편하고 비효과적인 신선식품 관리 시스템을 개선하겠다는 거창한 목표 이전에,

그저 "안전하고 편하게" 바나나우유를 마시고 싶다는 것이 이번 프로젝트의 시작점이었습니다.

**Comment by Tim-Lee0001** [comment]
### PainPoint

현재 수기로 관리 중인 신선식품은 2가지 특징이 있습니다. 

첫번째, 관리해야할 물품이 너무 많습니다. 시스템은 인당 연 435개씩 배정된 우유와 Px에서 구입하는 신선식품들을 관리해아합니다. 그러나 그 양은 수기로 관리하기에 애초에 무리가 있는 양입니다.

두번째, "꼭" 기한을 지켜야 합니다. 어느 집이든 상한음식이 "하나도" 없는 집은 없습니다. 그러나 군대는 그 조직의 특성상 식중독 예방을 위해 기한을 엄수할 수 밖에 없습니다.

이러한 특성 때문에 병사들은 개인적으로 휴대폰에 알람을 맞춰두기도 하고, 간부님들께서도 매번 냉장고를 확인해야하는 번거로움을 겪고 있습니다. 

이로 인해 개인적의 관점에선, 귀찮고 실수를 용납하지 않는 일일과업이 생겼으며 다른 곳에 쓸 수 있는 에너지를 낭비하게 됩니다. 

이를 군대라는 집단의 관점에서 보면, 인력의 낭비일 뿐더러 복잡한 관리시스템으로 인해 식중독의 위험을 효과적으로 줄이지 못하고 있는 상황입니다.

**Comment by Tim-Lee0001** [comment]
### Objective

"냉장고를 부탁해!"는 3가지 목표를 두고 기획 및 개발을 진행하였습니다.

첫번째, AI카메라를 활용한 신선식품의 체계적인 관리를 통해 "장염, 식중독" 등의 질병을 예방하고, 이를 통해 부대 전투력 상승에 기여하고자 합니다.

두번째, 네임펜을 통한 불편한 이름주기법을 쉽고 빠른 영수증 및 바코드 스캐닝으로 개선하고자 합니다. 이를 통해 식품 주인 파악을 용이하게 하고 도난을 방지하고자 합니다.

세번째, 간부님들께서 일일이 돌아다니지 않고 휴대폰 앱을 통한 냉장고 속 상태를 파악할 수 있도록 실시간 통계를 제공할 것 입니다. 이를 통해 냉장고를 청결하게 관리하도록 쉽게 지시할 수 있습니다.

본 프로젝트를 성공적으로 수행한다면, 눈길을 골목식당에 돌려보고자 합니다. "프랜차이즈가 아닌" 골목식당 사장님들은 우리 장병들과 다를 바 없이 식자재 관리 문제에 어려움을 겪고 있습니다. "백종원의 골목식당"에서 보듯, 체계적으로 관리되지 않은 식자재로 인해 위생 문제가 발생하고 있고, 이를 인지하고 있지만 개선하기 쉽지 않습니다. 기술 적용 과정에서의 단가를 낮추고 요식업에 맞는 요소들을 추가한다면 골목식당 사장님들께 도움이 되지 않을까 생각합니다.

마지막으로 조금 큰 바람이지만, 전 부대에 시스템이 적용되어 영수증 스캔을 이용한 소비 데이터를 축적할 수 있다면 "장병들의 금융을 책임지는 서비스"로의 전환도 고려하고자 합니다. 현재 장병의 월급이 급속도로 인상됨에 따라 2025년에는 월급이 205만원에 달하게 됩니다. 따라서 장병들의 소비패턴을 분석하고 올바른 소비습관을 제시하는 가계부 앱이라는 다음 단계로 넘어가면서 사용자를 늘리고, 이에 따라 자연스럽게 생기는 경제적 합의력을 바탕으로, 금융권에서 장병들에게 어울리는 상품을 경쟁적으로 제시하는 플랫폼을 제공하고자 합니다.

저희는 이 프로젝트를 통해, 언제나 문제가 되는 식중독 문제와 도난문제를 앱서비스와 AI를 통해 해결하고자 했습니다. 냉장고는 삶에 밀접하게 연관되어있고, 어디에서나 많이 사용하고 있기 때문에 글로벌한 솔루션이 될 수 있을 것이라 생각합니다. 또 이 과정에서 얻어지는 데이터는 의식주에서 "식"을 다룬다는 것을 고려할 때, 활용가치가 높기에 무궁무진한 확장을 기대할 수 있을 것입니다.

**Comment by Tim-Lee0001** [comment]
일단 이정도로 개요를 잡으면 될것 같습니다. 일단은 이슈를 닫겠습니다!
멘토링을 하며 조금 더 수정사항 반영해보도록 하겠습니다.
