### ISSUE TITLE
Design User Interface & Information Architecture

### ISSUE THREAD

**Issue by hmc0105** [osamhack2022/APP_FreshPlus_TakeCareMyRefrigerator#20]
### Introduction
개발목적을 바탕으로, UI 디자인을 완성하고 아래 Comment를 통해 공유해주시면 좋겠습니다.
@Tim-Lee0001 

### Requirements
1. **Figma** 를 통해 디자인을 진행해주십시오.
2.  IA의 경우 아래 링크를 참고해 제작해 이미지로 올려주시면 주시면 감사하겠습니다.
[IA, 메뉴구조도, 화면목록이 헷갈린다면?](https://yozm.wishket.com/magazine/detail/1606/)

### Pages
1. 로그인 페이지
    - 이메일과 비밀번호를 통한 로그인 페이지가 필요합니다.
2. 회원가입 페이지
    - 이메일, 비밀번호, 부대코드, 냉장고코드, 유저 타입(용사, 분대장, 간부)를 받을 페이지
3. 비밀번호 찾기 페이지
    - 이메일로 메일을 보내 비밀번호 초기화를 진행할 페이지
4. 개인(용사) 물품 페이지
    - 용사의 물품 통계를 보여주고, 세부 아이템 목록을 보여줄 페이지
5. 분대장용 냉장고 페이지
    - 냉장고 전체의 통계를 보여주고, 속해있는 분대원들의 목록을 보여줄 리스트, 분실 혹은 미등록된 물품을 보여줄 페이지
6. 간부용 부대 전체 냉장고 페이지
    - 부대 전체의 냉장고 통계를 직관적으로 보여주고, 속해있는 냉장고들의 목록을 보여줄 페이지
7. 아이템 추가 페이지
    - 바코드, 영수증, 직접입력 3가지의 경우를 반영할 수 있는 아이템 추가 페이지

**Comment by Tim-Lee0001** [comment]
확인했습니다.
일단 진행중인 피그마 화면들 먼저 공유 드리고 IA의 경우 새로운 이슈로 올려드리겠습니다~!

**Comment by Tim-Lee0001** [comment]
![image](https://user-images.githubusercontent.com/112791236/193755423-3dedbc99-d1f1-40e7-a197-28cfcdf7a5dd.png)
회원 가입 및 로그인 창 디자인 입니다

**Comment by Tim-Lee0001** [comment]
자세한 디자인 및 Variants 는 Slack 통해 전달드린 피그마 링크에서 확인해주시면 감사하겠습니다
