### ISSUE TITLE
Require App Design Structure

### ISSUE THREAD

**Issue by hmc0105** [osamhack2022/APP_FreshPlus_TakeCareMyRefrigerator#6]
### Overview of Design

앱개발을 위한 도면을 제공해주시면 감사하겠습니다.

**Comment by Tim-Lee0001** [comment]
![플래시 및 회원가입화면](https://user-images.githubusercontent.com/112791236/192141405-2a9b9b32-b73d-4ee3-b22c-6a6385874099.PNG)

앱 이름은 신선함을 더하자는 의미에서 FreshPlus로 정했습니다.

회원가입 양식은 위의 사진과 같습니다!
이메일과 군번 중 어떤 것으로 개인별 인식을 할지 고민이 됩니다.
의견 주시면 좋겠습니다!

**Comment by Tim-Lee0001** [comment]
정보는 이름 -> 이메일 -> 부대코드 -> 비밀번호 순으로 입력을 받을 것 같습니다.

회원 유형이 관리자라면 냉장고를 선택할 필요가 없는데, 
회원유형과 냉장고의 좌우 위치를 바꾸는게 좋을까요?

**Comment by hmc0105** [comment]
옙 그렇게 해주시면, 서버와 연동할 코드를 준비하겠습니다. 

그리고 혹시, 앱 디자인마다 (로그인, 메인페이지 등등) github issue를 만드는 게 좋을까요?

**Comment by leedbswo107** [comment]
loginpage 진행중 firebase에서 기본으로 지원하는 방식에 이메일 방식이 있어 이메일을 이용한 로그인을 할거 같습니다. 그렇기에 회원가입을 할때 이메일로 인증 하는 것이 후에 비밀번호 재설정 부분에 효율적일거 같습니다.

각 페이지별 issue를 만드는게 좋은거 같습니다. 진행상황에 있어 놓치는 부분에 대해 체크할 수 있는 부분이 될거 같고, 검토시간을 갖을 수 있을거 같아 각 페이지별로 issue 만드는 방향이 프로젝트 진행에 효과적일거 같습니다.
